language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

matrix:
  include:
    - python: 2.7
      env: EXAMPLES=true
    - python: 3.4
      env: EXAMPLES=true
    - python: 3.4
      env: NOSE_WITH_COVERAGE=y NOSE_COVER_PACKAGE=rsfmodel

addons:
  apt:
    packages:
    - libblas3gf
    - liblapack3gf

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then
      conda config --add channels https://conda.binstar.org/astropy-ci-extras;
    fi;
  - conda create -n Travis --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose
  - source activate Travis
  - if [[ $NOSE_WITH_COVERAGE == y ]]; then
      conda install --yes coverage;
    fi;

install:
  - python setup.py install

script:
    - if [[ $EXAMPLES == true ]]; then
        cd examples;
        echo backend:agg > matplotlibrc;
        MPLBACKEND='agg' python test_examples.py;
      else
        nosetests;
      fi

after_success:
  - if [[ $NOSE_WITH_COVERAGE == y ]]; then
      pip install coveralls;
      coveralls;
    fi;
